## Feature Selection

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
credit = pd.read_csv('Credit.csv')

In [4]:
credit.shape

(400, 11)

In [5]:
n = 400

In [6]:
credit[:5]

Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
0   14.891   3606     283      2   34         11    Male      No     Yes   
1  106.025   6645     483      3   82         15  Female     Yes     Yes   
2  104.593   7075     514      4   71         11    Male      No      No   
3  148.924   9504     681      3   36         11  Female      No      No   
4   55.882   4897     357      2   68         16    Male      No     Yes   

   Ethnicity  Balance  
0  Caucasian      333  
1      Asian      903  
2      Asian      580  
3      Asian      964  
4  Caucasian      331

In [7]:
credit.Ethnicity.unique()

array(['Caucasian', 'Asian', 'African American'], dtype=object)

In [8]:
pd.value_counts(credit.Ethnicity)

Caucasian           199
Asian               102
African American     99
Name: Ethnicity, dtype: int64

In [9]:
# Encode categorical vars

In [10]:
credit1 = pd.get_dummies(credit,columns = ['Gender','Student','Married','Ethnicity'],
                         drop_first = True)

In [11]:
credit1[:5]

Income  Limit  Rating  Cards  Age  Education  Balance  Gender_Female  \
0   14.891   3606     283      2   34         11      333              0   
1  106.025   6645     483      3   82         15      903              1   
2  104.593   7075     514      4   71         11      580              0   
3  148.924   9504     681      3   36         11      964              1   
4   55.882   4897     357      2   68         16      331              0   

   Student_Yes  Married_Yes  Ethnicity_Asian  Ethnicity_Caucasian  
0            0            1                0                    1  
1            1            1                1                    0  
2            0            0                1                    0  
3            0            0                1                    0  
4            0            1                0                    1

In [12]:
credit[:5]

Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
0   14.891   3606     283      2   34         11    Male      No     Yes   
1  106.025   6645     483      3   82         15  Female     Yes     Yes   
2  104.593   7075     514      4   71         11    Male      No      No   
3  148.924   9504     681      3   36         11  Female      No      No   
4   55.882   4897     357      2   68         16    Male      No     Yes   

   Ethnicity  Balance  
0  Caucasian      333  
1      Asian      903  
2      Asian      580  
3      Asian      964  
4  Caucasian      331

In [13]:
# split response Y, predictors X

In [14]:
Y = credit1.Balance
X = credit1.drop(columns = 'Balance', axis = 1)

In [15]:
# fit full model

In [16]:
model1 = LinearRegression().fit(X,Y)

In [17]:
# sklearn finds MSE as SSE/n

In [18]:
MSE = mean_squared_error(Y,model1.predict(X))
MSE

9466.825476694461

In [19]:
SSE = MSE * len(Y)
SSE

3786730.1906777844

In [20]:
R_squared = model1.score(X,Y)

In [21]:
R_squared

0.9551015633651758

In [ ]:
# library useful to compute combinatorial numbers

In [22]:
from scipy.special import comb

In [27]:
comb(11,2)

55.0

In [25]:
# function returns SSE, R-squared

In [23]:
def get_sse(X,Y):
    model_k = LinearRegression().fit(X,Y)
    SSE = mean_squared_error(Y,model_k.predict(X))*len(Y)
    R_squared = model_k.score(X,Y)
    return SSE, R_squared

In [24]:
SSE, R_squared = get_sse(X,Y)

In [25]:
SSE

3786730.1906777844

In [26]:
R_squared

0.9551015633651758

In [27]:
# Create four empty lists

In [28]:
SSE_list, R2_list, feature_list, num_features = [],[],[],[]

In [ ]:
# library useful to select subsets from a collection of items

In [29]:
import itertools

In [30]:
col_names = X.columns
col_names

Index(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education',
       'Gender_Female', 'Student_Yes', 'Married_Yes', 'Ethnicity_Asian',
       'Ethnicity_Caucasian'],
      dtype='object')

In [31]:
p = len(X.columns)
p

11

In [32]:
itertools.combinations(col_names,2)

In [33]:
list(itertools.combinations(col_names,2))

[('Income', 'Limit'),
 ('Income', 'Rating'),
 ('Income', 'Cards'),
 ('Income', 'Age'),
 ('Income', 'Education'),
 ('Income', 'Gender_Female'),
 ('Income', 'Student_Yes'),
 ('Income', 'Married_Yes'),
 ('Income', 'Ethnicity_Asian'),
 ('Income', 'Ethnicity_Caucasian'),
 ('Limit', 'Rating'),
 ('Limit', 'Cards'),
 ('Limit', 'Age'),
 ('Limit', 'Education'),
 ('Limit', 'Gender_Female'),
 ('Limit', 'Student_Yes'),
 ('Limit', 'Married_Yes'),
 ('Limit', 'Ethnicity_Asian'),
 ('Limit', 'Ethnicity_Caucasian'),
 ('Rating', 'Cards'),
 ('Rating', 'Age'),
 ('Rating', 'Education'),
 ('Rating', 'Gender_Female'),
 ('Rating', 'Student_Yes'),
 ('Rating', 'Married_Yes'),
 ('Rating', 'Ethnicity_Asian'),
 ('Rating', 'Ethnicity_Caucasian'),
 ('Cards', 'Age'),
 ('Cards', 'Education'),
 ('Cards', 'Gender_Female'),
 ('Cards', 'Student_Yes'),
 ('Cards', 'Married_Yes'),
 ('Cards', 'Ethnicity_Asian'),
 ('Cards', 'Ethnicity_Caucasian'),
 ('Age', 'Education'),
 ('Age', 'Gender_Female'),
 ('Age', 'Student_Yes'),
 ('Age'

In [34]:
list(range(1,p+1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [36]:
for k in range(1,p+1):
    for subset in itertools.combinations(X.columns,k):
        temp = get_sse(X[list(subset)],Y)

        SSE_list.append(temp[0])
        R2_list.append(temp[1])
        feature_list.append(subset)
        num_features.append(len(subset))

In [ ]:
# Create dataframe with 4 cols

In [37]:
df = pd.DataFrame(num_features,columns=['n_features'])

In [38]:
df['features'] = feature_list

In [39]:
df['R-squared'] = R2_list

In [40]:
SSE_list[:5]

[66208744.51078422,
 21715656.6591137,
 21435122.03273295,
 83709496.36968988,
 84339627.88174878]

In [41]:
SSE_list2 = np.round(SSE_list,0)

In [42]:
df['SSE'] = SSE_list2

In [43]:
df.shape

(2047, 4)

In [44]:
2**11

2048

In [45]:
df[:13]

n_features                features  R-squared         SSE
0            1               (Income,)   0.214977  66208745.0
1            1                (Limit,)   0.742522  21715657.0
2            1               (Rating,)   0.745848  21435122.0
3            1                (Cards,)   0.007475  83709496.0
4            1                  (Age,)   0.000003  84339628.0
5            1            (Education,)   0.000065  84334431.0
6            1        (Gender_Female,)   0.000461  84301020.0
7            1          (Student_Yes,)   0.067090  78681540.0
8            1          (Married_Yes,)   0.000032  84337197.0
9            1      (Ethnicity_Asian,)   0.000096  84331792.0
10           1  (Ethnicity_Caucasian,)   0.000011  84339000.0
11           2         (Income, Limit)   0.871107  10870832.0
12           2        (Income, Rating)   0.875118  10532541.0

In [46]:
# group by n_features

In [47]:
df.groupby(['n_features'])['R-squared'].max()

n_features
1     0.745848
2     0.875118
3     0.949879
4     0.953580
5     0.954161
6     0.954688
7     0.954817
8     0.954888
9     0.954964
10    0.955047
11    0.955102
Name: R-squared, dtype: float64

In [48]:
best_r2 = df.groupby(['n_features'])['R-squared'].max()

In [ ]:
# dataframe with best single predictor

In [49]:
df2 = df[df['R-squared'] == best_r2[1]]
df2

n_features   features  R-squared         SSE
2           1  (Rating,)   0.745848  21435122.0

In [50]:
# dataframe with best two predictors

In [51]:
df2 = df[df['R-squared'] == best_r2[2]]
df2

n_features          features  R-squared         SSE
12           2  (Income, Rating)   0.875118  10532541.0

In [ ]:
# dataframe with best subsets of predictors

In [53]:
df2 = df[df['R-squared'] == best_r2[1]]

In [54]:
for i in range(2,12):
    df2 = df2.append(df[df['R-squared'] == best_r2[i]])

In [55]:
df2

n_features                                           features  \
2              1                                          (Rating,)   
12             2                                   (Income, Rating)   
79             3                      (Income, Rating, Student_Yes)   
242            4                (Income, Limit, Cards, Student_Yes)   
564            5        (Income, Limit, Rating, Cards, Student_Yes)   
1025           6   (Income, Limit, Rating, Cards, Age, Student_Yes)   
1490           7  (Income, Limit, Rating, Cards, Age, Gender_Fem...   
1826           8  (Income, Limit, Rating, Cards, Age, Gender_Fem...   
1990           9  (Income, Limit, Rating, Cards, Age, Gender_Fem...   
2040          10  (Income, Limit, Rating, Cards, Age, Gender_Fem...   
2046          11  (Income, Limit, Rating, Cards, Age, Education,...   

      R-squared         SSE  
2      0.745848  21435122.0  
12     0.875118  10532541.0  
79     0.949879   4227219.0  
242    0.953580   3915058.0  
564    0.954161   3866091.0  
1025   0.954688   3821620.0  
1490   0.954817   3810759.0  
1826   0.954888   3804746.0  
1990   0.954964   3798367.0  
2040   0.955047   3791345.0  
2046   0.955102   3786730.0

In [56]:
# increase col width

In [57]:
pd.set_option('display.max_colwidth',190)

In [58]:
df2

n_features  \
2              1   
12             2   
79             3   
242            4   
564            5   
1025           6   
1490           7   
1826           8   
1990           9   
2040          10   
2046          11   

                                                                                                                           features  \
2                                                                                                                         (Rating,)   
12                                                                                                                 (Income, Rating)   
79                                                                                                    (Income, Rating, Student_Yes)   
242                                                                                             (Income, Limit, Cards, Student_Yes)   
564                                                                                     (Income, Limit, Rating, Cards, Student_Yes)   
1025                                                                               (Income, Limit, Rating, Cards, Age, Student_Yes)   
1490                                                                (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes)   
1826                                               (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes, Ethnicity_Asian)   
1990                                  (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes, Married_Yes, Ethnicity_Asian)   
2040             (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes, Married_Yes, Ethnicity_Asian, Ethnicity_Caucasian)   
2046  (Income, Limit, Rating, Cards, Age, Education, Gender_Female, Student_Yes, Married_Yes, Ethnicity_Asian, Ethnicity_Caucasian)   

      R-squared         SSE  
2      0.745848  21435122.0  
12     0.875118  10532541.0  
79     0.949879   4227219.0  
242    0.953580   3915058.0  
564    0.954161   3866091.0  
1025   0.954688   3821620.0  
1490   0.954817   3810759.0  
1826   0.954888   3804746.0  
1990   0.954964   3798367.0  
2040   0.955047   3791345.0  
2046   0.955102   3786730.0

In [ ]:
# Rating is best predictor, Education is the worst

In [59]:
# add AIC, adj R-squared columns

In [60]:
df2['AIC'] = n * np.log(df2['SSE']/n) + 2* df2['n_features']

In [62]:
df2['adj_R-squared'] = 1 - ((1 - df2['R-squared'])*(n-1)/(n - df2['n_features'] - 1))

In [63]:
df2

n_features  \
2              1   
12             2   
79             3   
242            4   
564            5   
1025           6   
1490           7   
1826           8   
1990           9   
2040          10   
2046          11   

                                                                                                                           features  \
2                                                                                                                         (Rating,)   
12                                                                                                                 (Income, Rating)   
79                                                                                                    (Income, Rating, Student_Yes)   
242                                                                                             (Income, Limit, Cards, Student_Yes)   
564                                                                                     (Income, Limit, Rating, Cards, Student_Yes)   
1025                                                                               (Income, Limit, Rating, Cards, Age, Student_Yes)   
1490                                                                (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes)   
1826                                               (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes, Ethnicity_Asian)   
1990                                  (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes, Married_Yes, Ethnicity_Asian)   
2040             (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes, Married_Yes, Ethnicity_Asian, Ethnicity_Caucasian)   
2046  (Income, Limit, Rating, Cards, Age, Education, Gender_Female, Student_Yes, Married_Yes, Ethnicity_Asian, Ethnicity_Caucasian)   

      R-squared         SSE          AIC  adj_R-squared  
2      0.745848  21435122.0  4357.630721       0.745210  
12     0.875118  10532541.0  4075.406247       0.874489  
79     0.949879   4227219.0  3712.236136       0.949499  
242    0.953580   3915058.0  3683.550462       0.953110  
564    0.954161   3866091.0  3680.515972       0.953579  
1025   0.954688   3821620.0  3677.888171       0.953996  
1490   0.954817   3810759.0  3678.749757       0.954010  
1826   0.954888   3804746.0  3680.118098       0.953965  
1990   0.954964   3798367.0  3681.446899       0.953924  
2040   0.955047   3791345.0  3682.706739       0.953891  
2046   0.955102   3786730.0  3684.219544       0.953829

In [64]:
# AIC best model

In [65]:
df2.AIC.min()

3677.8881709385214

In [66]:
df2[df2.AIC == df2.AIC.min()]

n_features                                          features  R-squared  \
1025           6  (Income, Limit, Rating, Cards, Age, Student_Yes)   0.954688   

            SSE          AIC  adj_R-squared  
1025  3821620.0  3677.888171       0.953996

In [67]:
# Adj-R2 best model

In [68]:
df2['adj_R-squared'].max()

0.9540098163629882

In [69]:
max_R2 = df2['adj_R-squared'].max()
max_R2

0.9540098163629882

In [70]:
df2[df2['adj_R-squared'] == max_R2]

n_features  \
1490           7   

                                                             features  \
1490  (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes)   

      R-squared        SSE          AIC  adj_R-squared  
1490   0.954817  3810759.0  3678.749757        0.95401

## Predict with best Adj-R2 model

In [71]:
row7 = df2[df2['adj_R-squared'] == max_R2]

In [72]:
row7['features']

1490    (Income, Limit, Rating, Cards, Age, Gender_Female, Student_Yes)
Name: features, dtype: object

In [73]:
list2 = ['Income','Limit','Rating','Cards','Age','Gender_Female','Student_Yes']
list2

['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Gender_Female', 'Student_Yes']

In [74]:
X1 = X[list2]

In [75]:
X[:5]

Income  Limit  Rating  Cards  Age  Education  Gender_Female  Student_Yes  \
0   14.891   3606     283      2   34         11              0            0   
1  106.025   6645     483      3   82         15              1            1   
2  104.593   7075     514      4   71         11              0            0   
3  148.924   9504     681      3   36         11              1            0   
4   55.882   4897     357      2   68         16              0            0   

   Married_Yes  Ethnicity_Asian  Ethnicity_Caucasian  
0            1                0                    1  
1            1                1                    0  
2            0                1                    0  
3            0                1                    0  
4            1                0                    1

In [76]:
X1[:5]

Income  Limit  Rating  Cards  Age  Gender_Female  Student_Yes
0   14.891   3606     283      2   34              0            0
1  106.025   6645     483      3   82              1            1
2  104.593   7075     514      4   71              0            0
3  148.924   9504     681      3   36              1            0
4   55.882   4897     357      2   68              0            0

In [77]:
m1 = LinearRegression().fit(X1,Y)

In [78]:
m1.score(X1,Y)

0.9548166616899533

In [79]:
# predict Balance of customer with median income, limit, age, and 3 credit cards

In [81]:
pd.value_counts(credit.Gender)

Female    207
 Male     193
Name: Gender, dtype: int64

In [82]:
pd.value_counts(credit.Student)

No     360
Yes     40
Name: Student, dtype: int64

In [83]:
# will assume customer is female and not student

In [84]:
newval = X1.iloc[[1]]
newval

Income  Limit  Rating  Cards  Age  Gender_Female  Student_Yes
1  106.025   6645     483      3   82              1            1

In [85]:
newval.iat[0,0] = np.median(X1.Income)
newval.iat[0,1] = np.median(X1.Limit)
newval.iat[0,2] = np.median(X1.Rating)
newval.iat[0,4] = np.median(X1.Age)
newval.iat[0,3] = 3
newval.iat[0,6] = 0
newval

Income  Limit  Rating  Cards  Age  Gender_Female  Student_Yes
1  33.1155   4622     344      3   56              1            0

In [86]:
m1.predict(newval)

array([533.36233424])

In [105]:
m1.intercept_

-488.6158695292403

In [87]:
m1.coef_

array([-7.80363382e+00,  1.93623721e-01,  1.09404899e+00,  1.81091708e+01,
       -6.20653761e-01, -1.04531521e+01,  4.26581262e+02])

In [88]:
newval.values

array([[3.31155e+01, 4.62200e+03, 3.44000e+02, 3.00000e+00, 5.60000e+01,
        1.00000e+00, 0.00000e+00]])

In [92]:
np.dot(newval.values,m1.coef_) + m1.intercept_

array([533.36233424])

In [91]:
# fitted equation

In [104]:
[(round(n, 2)) for n in m1.coef_]

[-7.8, 0.19, 1.09, 18.11, -0.62, -10.45, 426.58]

In [ ]:
# customer is female and not student

In [ ]:
# yhat = -488.6 -7.8 Income + 0.19 Limit +1.09 Rating + 18.11 Cards -0.62 Age -10.45